# Generated by Django 2.1.7 on 2019-03-28 09:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 28, 9, 43, 51, 708194, tzinfo=utc)),
        ),
    ]
